version: '3.8'

services:
  storage: 
    image: redis:7.0.9-alpine
    restart: unless-stopped
    container_name: service_storage
    ports:
      - 6379:6379
    hostname: service_storage
    command:  redis-server --save 60 1 --loglevel warning 
    # --requirepass h0LY^Gr@IL@A$$essMentExercisE007
    volumes:
      - storage:/data
  app:
    container_name: service_app
    build:
      context: ./HolyGrailApp
    restart: unless-stopped
    depends_on:
      - storage
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=storage
      - REDIS_PORT=6379
      - REDIS_PASSWORD=h0LY^Gr@IL@A$$essMentExercisE007
      - SERVICE_ENV=development
      - SERVICE_PORT=3000
    links:
      - storage


volumes:
  storage:
    driver: local
  